name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache-dependency-path: ./src
      - name: Install dependencies
        run: go get .
        working-directory: ./src
      - name: Build
        run: go build -v ./...
        working-directory: ./src
      - name: Test with the Go CLI
        run: go test
        working-directory: ./src
